### ISSUE TITLE
是否可以考虑也在 Javlibrary 添加在 AVMOO 打开的按钮。

### ISSUE THREAD

**Issue by Dionysiakos** [hobbyfang/javOldDriver#13]

**Comment by hobbyfang** [comment]
推荐使用https://sleazyfork.org/en/scripts/377603-jav%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%AC

然后自己添加一下

**Comment by Dionysiakos** [comment]
> 推荐使用 [ https://sleazyfork.org/en/scripts/377603-jav%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%AC](https://sleazyfork.org/en/scripts/377603-jav%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%AC)
> 
> 然后自己添加一下

感谢推荐，非常好用。
