### ISSUE TITLE
最近几个版本在Javlibrary一些功能失效

### ISSUE THREAD

**Issue by LayneHe** [hobbyfang/javOldDriver#16]
Javlibrary的相关功能（比如说瀑布流和若干筛选功能,还有显示影片时间），在完全新的浏览器第一次安装脚本时是有效的。但是关闭一次浏览器后失效。

尝试重新安装脚本或重装TamperMonkey或换用暴力猴均不起作用。

这个问题在Chrome系浏览器和Firefox都出现。

**Comment by hobbyfang** [comment]
@JulyanHe 
我从v69更新到v80版本，没发现什么问题。你检查下自己的浏览器环境，或者提供更多的详细步骤和信息。如果存在普遍问题，应该有等多人反馈才对。

**Comment by sino1641** [comment]
刚刚也出现这样的问题，
无脑尝试重置，重启blabla之后发现
删掉油猴脚本里存储页的内容就好了。
@hobbyfang 希望作者有时间可以修复这个bug，感谢
