### ISSUE TITLE
希望能增加功能：匹配本地片库，方便查漏补缺

### ISSUE THREAD

**Issue by slarkcoder** [hobbyfang/javOldDriver#18]
比如使用 https://github.com/moyy996/AVDC 项目，可以刮削出本地的片库，将整个片库的目录树导出，可以得到片库里的包含所有番号的文件。

接下来可以用脚本将 jav 网站每部影片（其中包含的每个番号），和这个文件内容做匹配，方便确定本地的影片库中是否包含该影片，如果本地有该影片，可以直接在网页元素上做出标记。这比手动去匹配要方便很多，希望开发者能考虑支持。

**Comment by hobbyfang** [comment]
目前无此计划，你可以给avdc反馈去支持。建议只要和javlibrary的“已拥有”功能对接即可。我的脚本是根据“我想要”“看过了”“已拥有”的个人数据做基础数据来识别的，已阅的番号有标注识别背景色。
