### ISSUE TITLE
javbus网站使用本脚本后收藏变成乱码

### ISSUE THREAD

**Issue by zongzi78** [hobbyfang/javOldDriver#20]
这是开启脚本之前
![1](https://user-images.githubusercontent.com/50414162/77846923-f16e1c80-71eb-11ea-8d3d-fc71a3fd2cbd.PNG)
这是开了脚本之后
![2](https://user-images.githubusercontent.com/50414162/77846937-0d71be00-71ec-11ea-977a-c7a45de38f4c.PNG)

**Comment by hobbyfang** [comment]
相同问题，https://sleazyfork.org/zh-CN/forum/discussion/73110/x
