### ISSUE TITLE
今天怎么各种失效啊？javlibrary

### ISSUE THREAD

**Issue by lijxse** [hobbyfang/javOldDriver#3]
直接插进没效果，种子搜索没有了。
而且javlibrary这次的DDOS等了好久，以前等2秒就进去了，这次都半小时才进去，不过是Chrome的。
我进不去的时候换了火狐秒进的，但是火狐装了油猴+老司机还是失效的。

大家也这样吗？

**Comment by hobbyfang** [comment]
最近使用没有发现问题
