### ISSUE TITLE
咔失败了

### ISSUE THREAD

**Issue by horryruo** [hobbyfang/javOldDriver#30]
单个作品里面的功能正常,但是演员页面等不会自动拼接页面了,很奇怪,上个版本都可以

**Comment by hobbyfang** [comment]
没明白，请描述更多。把问题页面的地址发出来。

**Comment by horryruo** [comment]
比如,作品页面磁力链接功能显示正常
![image](https://user-images.githubusercontent.com/33121172/95539560-47384280-0a21-11eb-943f-59dd479acca3.png)

但是,所有影片不会自动瀑布流了
![image](https://user-images.githubusercontent.com/33121172/95539661-86ff2a00-0a21-11eb-9688-e5dbc06984a1.png)

选项是开启的
![image](https://user-images.githubusercontent.com/33121172/95539677-967e7300-0a21-11eb-871d-f60489d6575b.png)
重装过脚本也还是不行

**Comment by horryruo** [comment]
使用的是最新版chrome，最新版油猴

**Comment by horryruo** [comment]
关闭了所有扩展和插件，依旧不生效

**Comment by horryruo** [comment]
试了下老司机-完全体-改能拼接多页面，但是内页就混乱了。。

**Comment by horryruo** [comment]
用了个新浏览器，发现运行正常，区别就在于不能用的浏览器这边多了个储存
![image](https://user-images.githubusercontent.com/33121172/95570554-add95280-0a59-11eb-8af8-e02c49fd1438.png)
![image](https://user-images.githubusercontent.com/33121172/95570579-b3369d00-0a59-11eb-8eaa-84561e70189e.png)
删掉的话会报错
![image](https://user-images.githubusercontent.com/33121172/95570618-c184b900-0a59-11eb-81ca-258decd426c5.png)
请问怎么删掉这个储存。。。。

**Comment by horryruo** [comment]
![image](https://user-images.githubusercontent.com/33121172/95571761-87b4b200-0a5b-11eb-8d51-6d88a933ff4c.png)
console界面，好像运行失败？

**Comment by horryruo** [comment]
好像就最新网址失效，，以前的网址正常

**Comment by horryruo** [comment]
找到问题所在了。。旧网址加www能生效瀑布流，但是新网址加www不能瀑布流。。
