### ISSUE TITLE
有无兴趣给javdb做一个类似的插件

### ISSUE THREAD

**Issue by Sayaori** [hobbyfang/javOldDriver#36]
https://javdb5.com/
javbus是不是加载不了图片，或者速度非常慢，最近网站又改了排序方式，新旧混杂在一起，体验非常差
这个网站虽然点击标题也能做到离线到115的功能，但是返回是否成功很慢

**Comment by a8992595** [comment]
这网站确实还不错，资源也可以就是排版不太行！  可惜我也不会技术

**Comment by theprimone** [comment]
javdb 不是本来就很好用了吗？
