### ISSUE TITLE
提交一段BUG修复代码

### ISSUE THREAD

**Issue by ChnCdd** [hobbyfang/javOldDriver#38]
我不会用GITHUB，不知道怎么上传修改代码，发在这里希望作者能看到。

问题一：从blogjav获取预览图函数，当匹配不到图片时，if (img_array.length > 0)判断不生效后面，应该调用resolve(null);否则即使JavStore能取到图，这里也不显示。

问题二：blogjav图片选择器应更新为”find('.entry-content a img[data\-src*="pixhost."]');“，后面取地址改为”$(img_array[0]).data('src')“。

**Comment by cs6031667** [comment]
感谢老司机，终于又可以看blog高清图了

**Comment by hobbyfang** [comment]
感谢支持，问题二已经更新，问题一没有发现问题，你可以实际测试下。

**Comment by ChnCdd** [comment]
问题一确实存在，我改了以后才解决的。但是和问题二有关系，如果问题二能取到图片，问题一就不存在，如果问题二取不到图，问题一就会出现。

**Comment by hobbyfang** [comment]
你说blogjav图没有,javStore能取到图,这个我测试过了,显示javstore图正常.
