### ISSUE TITLE
请求添加https://www.btexe.la这个搜索网站

### ISSUE THREAD

**Issue by liangxyz** [hobbyfang/javOldDriver#5]
如题，这个网站资源很全，就是我不会添加，请问作者能帮忙添加下吗？谢谢
原来的torrentkitty.tv已经关站了

**Comment by hobbyfang** [comment]
这个网站需要人机身份验证,所以添加这个网站会导致体验很差,没什么用

**Comment by liangxyz** [comment]
> 这个网站需要人机身份验证,所以添加这个网站会导致体验很差,没什么用

这边测试下来，用hk的代理不会触发人机验证

**Comment by liangxyz** [comment]
> 这个网站需要人机身份验证,所以添加这个网站会导致体验很差,没什么用

或者请问大佬能不能给一个获取磁链的代码？我想替换掉脚本里的http://torrentkitty.tv/，因为不太懂html的知识，所以不会写代码，只会简单替换
