### ISSUE TITLE
页面布局的问题

### ISSUE THREAD

**Issue by emilybye** [hobbyfang/javOldDriver#6]
浏览器的宽度在一定范围内的时候，磁力链接表格的点击链接容易被缩小的预览图挡住。另外就是这个时候表格的宽度也没有填满浏览器右边还留有空白，里面内容反而挤在了一起。

使用的Chrome浏览器，当前站点只使用了该脚本。

<img width="807" alt="image" src="https://user-images.githubusercontent.com/38835019/60732172-f0b99a00-9f7b-11e9-885d-1719bb80310d.png">

**Comment by hobbyfang** [comment]
已处理，请更新版本试试
