### ISSUE TITLE
如何使用啊？

### ISSUE THREAD

**Issue by SJP-github** [hobbyfang/javOldDriver#8]
这个脚本下载下来之后不知道怎么用，有没有老司机带飞的

**Comment by hobbyfang** [comment]
自己到主页提供链接上去自己摸索一下或搜索下，网上有很多其他网友分享的教程。

**Comment by hobbyfang** [comment]
https://www.javbus.com/forum/forum.php?mod=viewthread&tid=49426  网友分享的教程，可以参考下。
